### ISSUE TITLE
[Question] There are cases where using wasi-threads with wasp1-threads in Node.js causes it to hang

### ISSUE THREAD

**Issue by bokuweb** [toyobayashi/wasm-util#2]
Thank you for the great work :)
There seems to be a specific case where it hangs when using `wasi-threads`, which can be reproduced with the following repository.

https://github.com/bokuweb/wasip1-threads-example

This repository can be run with the following command

``` sh
🦀 v1.82.0-nightly 
❯ cargo build --release --target=wasm32-wasip1-threads
❯ node index.js
30
```

However, it seems to deadlock when the following commented-out lines are uncommented. Do you have any insights on this?

https://github.com/bokuweb/wasip1-threads-example/blob/main/src/main.rs#L7

This case does not work in Node.js, but it works correctly in Wasmtime. Therefore, I believe there is no issue with the WebAssembly file itself, but do you have any thoughts on this?

``` sh
❯ wasmtime --version
wasmtime-cli 20.0.1 (d1feb032c 2024-05-03)
❯ wasmtime --dir=. --wasm-features=threads --wasi-modules=experimental-wasi-threads target/wasm32-wasip1-threads/release/wasp1-threads-example.wasm
[src/main.rs:7:13] "why. if you enable this line, this program will be hang with nodejs" = "why. if you enable this line, this program will be hang with nodejs"
30
```

**Comment by toyobayashi** [comment]
There are limitations in Node.js WASI API for wasi-threads. I have created https://github.com/bokuweb/wasip1-threads-example/pull/2 to your repo.

The problem is, even in child thread, you must call `wasi.start()` before you call `wasi_thread_start()`. Otherwise the `wasi` instance can not get the memory of wasm module (the `dbg!()` calls `fd_write`, which need to access wasm memory), that cause the child thread throws, without notifying then the internal `atomic.wait32` in`std::thread::spawn`, so the main thread stucks.

![image](https://github.com/user-attachments/assets/912da5e2-3163-42ff-82dc-6250423dd631)


To call start or initialize, the proxy hack in the PR is necessary.

**Comment by toyobayashi** [comment]
If you would like to use wasip1-threads in Node.js or browser without emnapi, highly recommend you take a look 
 https://github.com/toyobayashi/emnapi/tree/main/packages/wasi-threads, I handled many edge cases for child threads spawning like what Emscripten do.

**Comment by bokuweb** [comment]
@toyobayashi Thanks for your quick response, I'll try it. Thank you!!!!!!

**Comment by bokuweb** [comment]
@toyobayashi 

Sorry, may I ask one more question?
What is the name of this debugger?
How can I use it?

![image](https://github.com/user-attachments/assets/1204dc34-21b8-4b53-9f9e-f4844233dd83)

**Comment by toyobayashi** [comment]
It's just the VSCode builtin JavaScript debugger :)

In the PR I added `.vscode/launch.json` that allows you press F5 to start debugging. Add a breakpoint at the line `instance.exports.wasi_thread_start()`, press Step Into (F11) button when the debugger stop at it, then the debugger will enter wasm.

So appreciate your sponsorship!

**Comment by bokuweb** [comment]
@toyobayashi Thanks!!
